<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><ProjectReference Include="../../src/Core/Dustweave.Core.csproj" /></ItemGroup>  <ItemGroup><Using Include="BD2Daily" /></ItemGroup>
</Project>
