<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0-windows</TargetFramework><AllowUnsafeBlocks>true</AllowUnsafeBlocks><DefineConstants>DESKTOP</DefineConstants></PropertyGroup><ItemGroup><Compile Include="../shared/*.cs"/><Compile Include="../localization/*.cs"/><EmbeddedResource Include="../localization/*.json" LogicalName="Language.%(Filename)%(Extension)"/><Compile Include="../vendor/SharpMonoInjector/*.cs"/><Compile Include="../ipc/common/*.cs"/><Compile Include="../ipc/desktop/*.cs"/><ProjectReference Include="../compatibility/BD2FiendHunter.Compatibility.csproj"/></ItemGroup></Project>